
version: 2

models:
  - name: dim_products
    description: "Information about each greenery product"
    columns:
      - name: product_id
        description: "Unique product identifier, the primary key for this table"
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Name for each product"
        tests:
          - unique
          - not_null
      - name: price
        description: "Price per product item"
        tests:
          - positive_values
          - not_null
      - name: inventory
        description: "Inventory of product item"
        tests:
          - positive_values
          - not_null

  - name: dim_users
    description: "Information about each user at greenery"
    columns:
      - name: user_id
        description: "Unique user ID"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "User first name"
        tests:
          - not_null
      - name: last_name
        description: "User last name"
        tests:
          - not_null
      - name: email
        description: "User email address"
        tests:
          - not_null
      - name: phone_number
        description: "User phone number"
        tests:
          - not_null
      - name: created_at_utc
        description: "User phone number"
        tests:
          - not_null


  - name: fact_orders
    description: "Fact table with information about each greenery order"
    columns:
      - name: order_id
        description: "Unique order id"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Unique order id"
        tests:
          - not_null
      - name: order_cost
        description: "Cost of the order items"
        tests:
          - not_null
          - positive_values
      - name: shipping_cost
        description: "Cost of the shipping for the order"
        tests:
          - not_null
          - positive_values
      - name: order_total
        description: "Cost of the order items and shipping total for the order"
        tests:
          - not_null
          - positive_values
      - name: order_status
        description: "Cost of the order items and shipping total for the order"
        tests:
          - not_null
      - name: created_at_utc
        description: "Order created at timestamp"
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: string

  - name: fact_sessions
    description: "Fact table with information about each user session on the greenery site"
    columns:
      - name: session_id
        description: "The unique session ID"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "The unique user ID for the session"
        tests:
          - not_null
      - name: session_started_at_utc
        description: "The time in UTC that the session started at"
        tests:
          - not_null

  - name: fact_product_sessions
    description: "Fact table with information about each user session on the greenery site per product"
    columns:
      - name: session_id
        description: "The unique session ID"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "The unique user ID for the session"
        tests:
          - not_null
      - name: session_started_at_utc
        description: "The time in UTC that the session started at"
        tests:
          - not_null
      - name: product_id
        description: "The product ID viewed"
        tests:
          - not_null